name: nutriset
dependencies:
  - python=3.6
  - pip
  - numpy
  - pip:
    - dash==0.21.0
    - dash-renderer==0.11.3
    - dash-html-components==0.9.0
    - dash-core-components==0.18.1
    - plotly
    - requests